apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.labels.app }}
  name: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Values.labels.app }}
  type: {{ .Values.service.type }}